"""
seed_data.py — Constantes de dados para popular o banco de médicos brasileiros.
Importado por seed.py. Contém apenas dados (listas, dicts, tuples), sem lógica.

Baseado na taxonomia real do CFM/AMB e dados do sistema de saúde brasileiro.
"""

# ===========================================================================
# 1. ESPECIALIDADES_COMPLETAS
#    Mapeamento de todas as especialidades reconhecidas pelo CFM/AMB
#    com suas subespecialidades / áreas de atuação reais.
# ===========================================================================

ESPECIALIDADES_COMPLETAS = {
    "Cardiologia": [
        "Cardiologia Intervencionista",
        "Eletrofisiologia Cardíaca",
        "Ecocardiografia",
        "Cardio-Oncologia",
        "Insuficiência Cardíaca e Transplante",
        "Cardiopediatria",
        "Hemodinâmica",
        "Ergometria e Reabilitação Cardíaca",
        "Cardiologia do Esporte",
        "Cardiologia Nuclear",
    ],
    "Ortopedia e Traumatologia": [
        "Ombro e Cotovelo",
        "Joelho",
        "Coluna",
        "Quadril",
        "Mão e Microcirurgia",
        "Pé e Tornozelo",
        "Ortopedia Pediátrica",
        "Oncologia Ortopédica",
        "Trauma Esportivo / Medicina do Esporte",
        "Ortopedia do Trauma",
        "Reconstrução e Alongamento Ósseo",
    ],
    "Cirurgia Geral": [
        "Cirurgia do Aparelho Digestivo",
        "Cirurgia Videolaparoscópica",
        "Cirurgia Bariátrica e Metabólica",
        "Cirurgia do Trauma",
        "Cirurgia Oncológica",
        "Transplante de Órgãos",
        "Cirurgia Hepatobiliar",
        "Coloproctologia Cirúrgica",
        "Cirurgia de Parede Abdominal",
        "Cirurgia Minimamente Invasiva e Robótica",
    ],
    "Cirurgia Plástica": [
        "Cirurgia Reparadora",
        "Cirurgia Estética",
        "Microcirurgia Reconstrutiva",
        "Queimados",
        "Cirurgia Craniofacial",
        "Cirurgia da Mão",
        "Cirurgia Pós-Bariátrica",
        "Reconstrução Mamária",
    ],
    "Cirurgia Cardiovascular": [
        "Cirurgia de Revascularização Miocárdica",
        "Cirurgia Valvar",
        "Cirurgia de Aorta",
        "Cirurgia Cardíaca Minimamente Invasiva",
        "Cirurgia Cardíaca Pediátrica e Congênita",
        "Assistência Circulatória Mecânica",
        "Transplante Cardíaco",
    ],
    "Cirurgia Torácica": [
        "Cirurgia Torácica Oncológica",
        "Cirurgia Torácica Videoassistida (VATS)",
        "Cirurgia da Parede Torácica",
        "Transplante Pulmonar",
        "Broncoscopia Intervencionista",
        "Mediastinoscopia",
    ],
    "Cirurgia Vascular": [
        "Cirurgia Endovascular",
        "Cirurgia de Aorta e Grandes Vasos",
        "Cirurgia de Varizes",
        "Acessos Vasculares para Hemodiálise",
        "Cirurgia de Carótidas",
        "Cirurgia Venosa Profunda",
        "Pé Diabético",
    ],
    "Cirurgia de Cabeça e Pescoço": [
        "Oncologia de Cabeça e Pescoço",
        "Cirurgia de Tireoide e Paratireoide",
        "Cirurgia de Glândulas Salivares",
        "Cirurgia de Cavidade Oral e Orofaringe",
        "Cirurgia de Laringe e Hipofaringe",
        "Reconstrução de Cabeça e Pescoço",
        "Cirurgia de Base de Crânio",
    ],
    "Cirurgia Pediátrica": [
        "Cirurgia Neonatal",
        "Cirurgia Pediátrica Oncológica",
        "Cirurgia Pediátrica Urológica",
        "Cirurgia Pediátrica Torácica",
        "Cirurgia Minimamente Invasiva Pediátrica",
        "Cirurgia de Malformações Congênitas",
    ],
    "Neurocirurgia": [
        "Neurocirurgia de Coluna",
        "Neurocirurgia Vascular",
        "Neurocirurgia de Tumores",
        "Neurocirurgia Funcional e Estereotáxica",
        "Neurocirurgia Pediátrica",
        "Neurocirurgia da Epilepsia",
        "Neurocirurgia de Base de Crânio",
        "Neurocirurgia Endovascular",
        "Radiocirurgia",
        "Neuromodulação",
    ],
    "Dermatologia": [
        "Dermatologia Cosmética / Cosmiatria",
        "Dermato-Oncologia",
        "Dermatologia Pediátrica",
        "Tricologia",
        "Dermatopatologia",
        "Dermatologia Cirúrgica",
        "Cirurgia Micrográfica de Mohs",
        "Fototerapia",
        "Hansenologia",
        "Dermatologia Ocupacional",
    ],
    "Ginecologia e Obstetrícia": [
        "Ginecologia Oncológica",
        "Reprodução Assistida / Reprodução Humana",
        "Uroginecologia",
        "Mastologia Ginecológica",
        "Endometriose e Dor Pélvica",
        "Obstetrícia de Alto Risco / Medicina Fetal",
        "Ginecologia da Infância e Adolescência",
        "Endocrinologia Ginecológica",
        "Patologia do Trato Genital Inferior",
        "Sexologia",
    ],
    "Pediatria": [
        "Neonatologia",
        "Infectologia Pediátrica",
        "Cardiologia Pediátrica",
        "Neurologia Pediátrica / Neuropediatria",
        "Gastroenterologia Pediátrica",
        "Endocrinologia Pediátrica",
        "Pneumologia Pediátrica",
        "Nefrologia Pediátrica",
        "Reumatologia Pediátrica",
        "Alergia e Imunologia Pediátrica",
        "Terapia Intensiva Pediátrica",
        "Nutrologia Pediátrica",
        "Hematologia Pediátrica",
    ],
    "Neurologia": [
        "Neurologia Vascular (AVC)",
        "Epilepsia",
        "Neurologia do Sono",
        "Esclerose Múltipla e Neuroimunologia",
        "Neurointensivismo",
        "Doenças Neuromusculares",
        "Distúrbios do Movimento",
        "Cefaleias",
        "Neurologia Cognitiva e Comportamental (Demências)",
        "Neurofisiologia Clínica",
        "Neuropediatria",
    ],
    "Oftalmologia": [
        "Retina e Vítreo",
        "Glaucoma",
        "Córnea e Doenças Externas",
        "Catarata",
        "Estrabismo",
        "Oculoplástica",
        "Oftalmopediatria",
        "Cirurgia Refrativa",
        "Uveíte",
        "Oncologia Ocular",
        "Neuro-Oftalmologia",
    ],
    "Urologia": [
        "Uro-Oncologia",
        "Urologia Feminina",
        "Endourologia / Litíase Urinária",
        "Andrologia",
        "Urologia Pediátrica",
        "Transplante Renal Cirúrgico",
        "Urodinâmica",
        "Cirurgia Robótica Urológica",
        "Prótese Peniana",
        "Disfunção Miccional",
    ],
    "Psiquiatria": [
        "Psiquiatria Forense",
        "Psiquiatria da Infância e Adolescência",
        "Psicofarmacologia",
        "Dependência Química",
        "Psicogeriatria",
        "Psiquiatria de Emergência",
        "Transtornos do Humor",
        "Transtornos de Ansiedade",
        "Psiquiatria do Sono",
        "Neuromodulação (EMT/ETCC)",
    ],
    "Oncologia Clínica": [
        "Oncologia Clínica Geral",
        "Onco-Hematologia",
        "Oncologia Pediátrica",
        "Cuidados Paliativos",
        "Oncologia Ginecológica",
        "Oncologia Torácica",
        "Oncologia do Aparelho Digestivo",
        "Oncologia Urológica",
        "Imuno-Oncologia",
        "Oncogenética",
    ],
    "Endocrinologia e Metabologia": [
        "Diabetes Mellitus",
        "Tireoide",
        "Obesidade e Síndrome Metabólica",
        "Suprarrenal",
        "Osteoporose e Metabolismo Ósseo",
        "Endocrinologia Pediátrica",
        "Endocrinologia Reprodutiva",
        "Neuroendocrinologia",
        "Lipidologia",
        "Endocrinologia Oncológica",
    ],
    "Gastroenterologia": [
        "Hepatologia",
        "Endoscopia Digestiva",
        "Doenças Inflamatórias Intestinais",
        "Motilidade Digestiva / Neurogastroenterologia",
        "Gastroenterologia Pediátrica",
        "Pancreatologia",
        "Esôfago e Estômago",
        "Intestino Delgado",
        "Ecoendoscopia",
        "Transplante Hepático (acompanhamento clínico)",
    ],
    "Otorrinolaringologia": [
        "Otologia / Neurotologia",
        "Rinologia",
        "Laringologia e Voz",
        "Otorrinopediatria",
        "Cirurgia de Cabeça e Pescoço ORL",
        "Otoneurologia",
        "Medicina do Sono (ORL)",
        "Implante Coclear",
        "Rinoplastia",
        "Alergia e Imunologia ORL",
    ],
    "Anestesiologia": [
        "Anestesia Cardiotorácica",
        "Anestesia em Neurocirurgia",
        "Anestesia Obstétrica",
        "Anestesia Pediátrica",
        "Anestesia Regional e Bloqueios",
        "Medicina da Dor / Dor Crônica",
        "Anestesia em Cirurgia Bariátrica",
        "Terapia Intensiva (Anestesiologista)",
        "Anestesia Ambulatorial",
        "Cuidados Paliativos (Anestesiologista)",
    ],
    "Medicina do Esporte": [
        "Fisiologia do Exercício",
        "Traumatologia Esportiva",
        "Reabilitação Esportiva",
        "Cardiologia do Esporte",
        "Nutrologia Esportiva",
        "Medicina do Esporte de Alto Rendimento",
    ],
    "Geriatria e Gerontologia": [
        "Demências e Cuidados Cognitivos",
        "Cuidados Paliativos Geriátricos",
        "Ortogeriatria",
        "Cardiogeriatria",
        "Reabilitação Geriátrica",
        "Prevenção de Quedas e Fragilidade",
        "Polifarmácia e Desprescrição",
    ],
    "Reumatologia": [
        "Artrite Reumatoide",
        "Lúpus Eritematoso Sistêmico",
        "Espondiloartrites",
        "Vasculites Sistêmicas",
        "Fibromialgia e Dor Musculoesquelética",
        "Osteoartrite / Artrose",
        "Reumatologia Pediátrica",
        "Doenças Osteometabólicas",
        "Esclerose Sistêmica",
        "Miopatias Inflamatórias",
    ],
    "Pneumologia": [
        "Asma",
        "DPOC",
        "Pneumologia Intervencionista",
        "Doenças Intersticiais Pulmonares",
        "Infecções Pulmonares / Tuberculose",
        "Hipertensão Pulmonar",
        "Medicina do Sono (Pneumologia)",
        "Transplante Pulmonar (acompanhamento clínico)",
        "Fibrose Cística",
        "Oncologia Pulmonar",
    ],
    "Nefrologia": [
        "Hemodiálise",
        "Diálise Peritoneal",
        "Transplante Renal",
        "Nefrologia Pediátrica",
        "Glomerulopatias",
        "Injúria Renal Aguda",
        "Hipertensão Arterial Nefrológica",
        "Nefropatia Diabética",
        "Litíase Renal",
    ],
    "Hematologia e Hemoterapia": [
        "Onco-Hematologia",
        "Transplante de Medula Óssea",
        "Hemoterapia e Medicina Transfusional",
        "Distúrbios da Hemostasia e Trombose",
        "Anemias e Hemoglobinopatias",
        "Hematologia Pediátrica",
        "Terapia Celular",
        "Linfomas",
        "Leucemias",
    ],
    "Infectologia": [
        "HIV/AIDS",
        "Infecções Hospitalares e CCIH",
        "Infectologia Pediátrica",
        "Doenças Tropicais e Parasitárias",
        "Hepatites Virais",
        "Micologia Clínica",
        "Infectologia em Transplantes",
        "Antimicrobianos e Resistência Bacteriana",
        "Medicina do Viajante",
    ],
    "Medicina Intensiva": [
        "Terapia Intensiva Adulto",
        "Terapia Intensiva Pediátrica",
        "Terapia Intensiva Neonatal",
        "Terapia Intensiva Neurológica",
        "Terapia Intensiva Cardiológica",
        "Cuidados Pós-Operatórios Intensivos",
        "ECMO / Suporte Extracorpóreo",
    ],
    "Radiologia e Diagnóstico por Imagem": [
        "Neurorradiologia",
        "Radiologia Musculoesquelética",
        "Radiologia Abdominal",
        "Radiologia Torácica",
        "Radiologia Mamária",
        "Radiologia Intervencionista",
        "Ultrassonografia Geral",
        "Tomografia Computadorizada",
        "Ressonância Magnética",
        "Radiologia Pediátrica",
    ],
    "Medicina Nuclear": [
        "PET-CT",
        "Cintilografia Miocárdica",
        "Cintilografia Óssea",
        "Cintilografia Tireoidiana",
        "Radioimunoterapia",
        "Terapia com Iodo Radioativo",
        "Dosimetria",
    ],
    "Patologia / Anatomia Patológica": [
        "Citopatologia",
        "Dermatopatologia",
        "Patologia Cirúrgica",
        "Neuropatologia",
        "Hematopatologia",
        "Patologia Molecular",
        "Imuno-histoquímica",
        "Patologia Renal",
    ],
    "Medicina de Família e Comunidade": [
        "Atenção Primária à Saúde",
        "Saúde da Mulher na APS",
        "Saúde da Criança na APS",
        "Saúde do Idoso na APS",
        "Saúde Mental na APS",
        "Doenças Crônicas Não Transmissíveis",
        "Saúde do Trabalhador na APS",
    ],
    "Mastologia": [
        "Oncologia Mamária",
        "Cirurgia Oncoplástica da Mama",
        "Reconstrução Mamária",
        "Imaginologia Mamária",
        "Mastologia de Alto Risco",
        "Doenças Benignas da Mama",
    ],
    "Nutrologia": [
        "Nutrologia Clínica",
        "Nutrologia Pediátrica",
        "Nutrologia Esportiva",
        "Nutrologia Parenteral e Enteral",
        "Nutrologia Bariátrica",
        "Nutrologia do Idoso",
        "Obesidade e Síndrome Metabólica",
    ],
    "Acupuntura": [
        "Acupuntura Sistêmica",
        "Eletroacupuntura",
        "Auriculoterapia",
        "Acupuntura em Dor Crônica",
        "Acupuntura Obstétrica",
        "Acupuntura Estética",
    ],
    "Medicina do Trabalho": [
        "Ergonomia",
        "Perícia Médica Ocupacional",
        "Toxicologia Ocupacional",
        "Saúde Mental do Trabalhador",
        "Programa de Controle Médico de Saúde Ocupacional (PCMSO)",
        "Doenças Relacionadas ao Trabalho",
    ],
    "Medicina Legal e Perícia Médica": [
        "Perícia Criminal",
        "Perícia Cível",
        "Sexologia Forense",
        "Tanatologia",
        "Traumatologia Forense",
        "Psicopatologia Forense",
        "Identificação Médico-Legal",
    ],
    "Medicina Física e Reabilitação (Fisiatria)": [
        "Reabilitação Neurológica",
        "Reabilitação Musculoesquelética",
        "Reabilitação de Amputados",
        "Espasticidade",
        "Dor Crônica (Fisiatria)",
        "Reabilitação Cardiopulmonar",
        "Eletroneuromiografia",
        "Medicina Física do Esporte",
        "Acupuntura Médica (Fisiatria)",
    ],
    "Genética Médica": [
        "Genética Clínica",
        "Oncogenética",
        "Genética Pré-Natal",
        "Erros Inatos do Metabolismo",
        "Genética Cardiovascular",
        "Aconselhamento Genético",
        "Citogenética",
        "Genética Molecular",
    ],
    "Cirurgia do Aparelho Digestivo": [
        "Cirurgia Bariátrica e Metabólica",
        "Cirurgia Hepatobiliopancreática",
        "Cirurgia do Esôfago e Estômago",
        "Cirurgia do Intestino Delgado",
        "Cirurgia Colorretal",
        "Transplante Hepático",
        "Cirurgia Videolaparoscópica Digestiva",
        "Cirurgia Robótica Digestiva",
        "Hérnias Complexas",
    ],
    "Coloproctologia": [
        "Coloproctologia Oncológica",
        "Doenças Inflamatórias Intestinais (Cirúrgica)",
        "Cirurgia Minimamente Invasiva Colorretal",
        "Doenças Orificiais (Hemorroidas, Fissuras, Fístulas)",
        "Estomaterapia",
        "Constipação e Incontinência Fecal",
        "Cirurgia Robótica Colorretal",
    ],
    "Angiologia": [
        "Doença Arterial Periférica",
        "Trombose Venosa Profunda",
        "Insuficiência Venosa Crônica",
        "Linfedema",
        "Pé Diabético (Angiologia)",
        "Úlceras Vasculares",
        "Angiologia Diagnóstica (Eco-Doppler)",
    ],
    "Alergia e Imunologia": [
        "Asma Alérgica",
        "Rinite Alérgica",
        "Dermatite Atópica",
        "Alergia Alimentar",
        "Urticária e Angioedema",
        "Imunodeficiências Primárias",
        "Alergia a Medicamentos",
        "Imunoterapia Específica",
        "Anafilaxia",
    ],
    "Radioterapia": [
        "Radioterapia de Intensidade Modulada (IMRT)",
        "Radiocirurgia Estereotáxica",
        "Braquiterapia",
        "Radioterapia Pediátrica",
        "Radioterapia Intraoperatória",
        "Radioterapia Corporal Estereotáxica (SBRT)",
        "Próton-Terapia",
    ],
    "Medicina de Emergência": [
        "Urgência e Emergência Clínica",
        "Trauma e Emergência Cirúrgica",
        "Emergência Pediátrica",
        "Ultrassonografia Point-of-Care (POCUS)",
        "Toxicologia de Emergência",
        "Suporte Avançado de Vida",
        "Medicina de Desastres",
    ],
    "Cirurgia da Mão": [
        "Microcirurgia da Mão",
        "Traumatologia da Mão e Punho",
        "Cirurgia de Nervos Periféricos",
        "Reimplantes e Transferências",
        "Doenças Degenerativas da Mão",
        "Malformações Congênitas da Mão",
        "Tenossinovites e Síndromes Compressivas",
    ],
    "Homeopatia": [
        "Homeopatia Pediátrica",
        "Homeopatia em Doenças Crônicas",
        "Homeopatia em Alergia",
        "Homeopatia Clínica Geral",
    ],
    "Medicina Preventiva e Social": [
        "Epidemiologia",
        "Administração em Saúde",
        "Vigilância em Saúde",
        "Saúde Coletiva",
        "Promoção da Saúde",
    ],
}


# ===========================================================================
# 2. PROCEDIMENTOS_POR_ESPECIALIDADE
#    Procedimentos reais com códigos TUSS (quando disponíveis).
# ===========================================================================

PROCEDIMENTOS_POR_ESPECIALIDADE = {
    "Cardiologia": [
        ("Ecocardiograma Transtorácico", "40304361"),
        ("Ecocardiograma Transesofágico", "40304370"),
        ("Eletrocardiograma de 12 Derivações", "40301010"),
        ("Teste Ergométrico", "40302016"),
        ("Cateterismo Cardíaco Diagnóstico", "30607021"),
        ("Angioplastia Coronária com Stent", "30607307"),
        ("Holter 24h", "40302199"),
        ("MAPA 24h", "40302210"),
        ("Implante de Marca-Passo Definitivo", "30607110"),
        ("Implante de CDI (Cardioversor-Desfibrilador)", "30607128"),
        ("Ablação por Radiofrequência", "30607136"),
        ("Estudo Eletrofisiológico Intracardíaco", "30607144"),
        ("Pericardiocentese", "30607152"),
        ("Ressonância Magnética Cardíaca", "41001150"),
        ("Angiotomografia Coronariana", "41001168"),
    ],
    "Ortopedia e Traumatologia": [
        ("Artroscopia de Ombro Diagnóstica", "30724073"),
        ("Reparo do Manguito Rotador (Artroscópico)", "30724090"),
        ("Reparo do Manguito Rotador (Aberto)", "30724091"),
        ("Cirurgia de Bankart (Instabilidade Anterior do Ombro)", "30724108"),
        ("Cirurgia de Latarjet (Instabilidade Anterior com Perda Óssea)", "30724109"),
        ("Artroplastia Total do Ombro", "30726027"),
        ("Artroplastia Reversa do Ombro", "30726028"),
        ("Descompressão Subacromial Artroscópica", "30724116"),
        ("Tenodese do Bíceps (Artroscópica)", "30724124"),
        ("Tenotomia do Bíceps (Artroscópica)", "30724125"),
        ("Reparo SLAP (Superior Labrum Anterior to Posterior)", "30724126"),
        ("Acromioplastia", "30724127"),
        ("Osteossíntese de Fratura de Úmero Proximal", "30724128"),
        ("Liberação Artroscópica de Capsulite Adesiva", "30724129"),
        ("Artroscopia de Joelho", "30724065"),
        ("Reconstrução do LCA (Ligamento Cruzado Anterior)", "30724081"),
        ("Reconstrução do LCP (Ligamento Cruzado Posterior)", "30724082"),
        ("Meniscectomia Artroscópica", "30724083"),
        ("Reparo Meniscal Artroscópico", "30724084"),
        ("Artroplastia Total do Joelho", "30724103"),
        ("Artroplastia Unicompartimental do Joelho", "30724104"),
        ("Artroplastia Total do Quadril", "30726019"),
        ("Osteossíntese de Fratura de Fêmur Proximal", "30726124"),
        ("Artrodese de Coluna Lombar (TLIF/PLIF)", "30715050"),
        ("Discectomia Lombar / Microdiscectomia", "30715051"),
        ("Descompressão de Canal Lombar", "30715068"),
        ("Artrodese de Coluna Cervical Anterior", "30715069"),
        ("Correção de Hálux Valgo (Joanete)", "30728010"),
        ("Osteossíntese de Fratura de Tornozelo", "30728020"),
        ("Liberação do Túnel do Carpo", "30730010"),
        ("Reconstrução de Ligamentos do Tornozelo", "30728030"),
    ],
    "Cirurgia Geral": [
        ("Colecistectomia Laparoscópica", "30606123"),
        ("Herniorrafia Inguinal (Lichtenstein)", "30704019"),
        ("Herniorrafia Inguinal Laparoscópica (TEP/TAPP)", "30704020"),
        ("Apendicectomia Laparoscópica", "30606131"),
        ("Gastrectomia Total", "30606107"),
        ("Gastrectomia Subtotal", "30606108"),
        ("Fundoplicatura Laparoscópica (Nissen)", "30606115"),
        ("Esplenectomia Laparoscópica", "30606069"),
        ("Hemorroidectomia", "30607250"),
        ("Hernioplastia Incisional (Eventroplastia)", "30704025"),
        ("Cirurgia Bariátrica — Bypass Gástrico em Y de Roux", "30606200"),
        ("Cirurgia Bariátrica — Sleeve (Gastrectomia Vertical)", "30606201"),
        ("Tireoidectomia Total", "30601080"),
        ("Paratireoidectomia", "30601081"),
        ("Adrenalectomia Laparoscópica", "30601082"),
    ],
    "Cirurgia Plástica": [
        ("Mamoplastia de Aumento com Implante", "30308049"),
        ("Mastopexia (Lifting de Mama)", "30308050"),
        ("Mamoplastia Redutora", "30308051"),
        ("Abdominoplastia", "30308030"),
        ("Lipoaspiração", "30308065"),
        ("Rinoplastia Estética", "30404047"),
        ("Ritidoplastia (Lifting Facial)", "30308057"),
        ("Blefaroplastia Superior e Inferior", "30309010"),
        ("Otoplastia", "30309029"),
        ("Reconstrução Mamária com Retalho TRAM", "30308070"),
        ("Reconstrução Mamária com Expansor/Prótese", "30308071"),
        ("Enxerto de Gordura (Lipofilling)", "30308072"),
        ("Dermolipectomia de Braço (Braquioplastia)", "30308073"),
        ("Dermolipectomia de Coxa (Cruroplastia)", "30308074"),
        ("Cirurgia Reparadora de Queimaduras", "30308075"),
    ],
    "Cirurgia Cardiovascular": [
        ("Revascularização Miocárdica (Ponte de Safena/Mamária)", "30607030"),
        ("Troca Valvar Aórtica", "30607040"),
        ("Troca Valvar Mitral", "30607041"),
        ("Plastia Valvar Mitral", "30607042"),
        ("Implante de TAVI (Válvula Aórtica Transcateter)", "30607043"),
        ("Correção de Comunicação Interatrial (CIA)", "30607050"),
        ("Correção de Comunicação Interventricular (CIV)", "30607051"),
        ("Correção de Tetralogia de Fallot", "30607052"),
        ("Cirurgia da Aorta Ascendente (Bentall)", "30607060"),
        ("Correção de Aneurisma de Aorta Abdominal", "30607061"),
        ("Cirurgia de Dissecção de Aorta", "30607062"),
        ("Implante de ECMO (Oxigenação por Membrana Extracorpórea)", "30607070"),
        ("Transplante Cardíaco", "30607080"),
    ],
    "Cirurgia Torácica": [
        ("Lobectomia Pulmonar (VATS)", "30608010"),
        ("Pneumonectomia", "30608011"),
        ("Segmentectomia Pulmonar (VATS)", "30608012"),
        ("Mediastinoscopia", "30608020"),
        ("Timectomia (VATS)", "30608021"),
        ("Drenagem Torácica", "30608030"),
        ("Pleuroscopia / Toracoscopia Diagnóstica", "30608031"),
        ("Pleurodese Química", "30608032"),
        ("Decorticação Pulmonar", "30608033"),
        ("Ressecção de Tumor de Mediastino", "30608040"),
        ("Reparo de Hérnia Diafragmática", "30608050"),
        ("Broncoscopia Rígida Intervencionista", "30608060"),
    ],
    "Cirurgia Vascular": [
        ("Endarterectomia de Carótida", "30609010"),
        ("Angioplastia Periférica com Stent", "30609020"),
        ("Bypass Femoropoplíteo", "30609030"),
        ("Correção de Aneurisma de Aorta Abdominal (Endovascular)", "30609040"),
        ("Safenectomia / Cirurgia de Varizes", "30609050"),
        ("Laser Endovenoso para Varizes", "30609051"),
        ("Escleroterapia de Varizes", "30609052"),
        ("Confecção de Fístula Arteriovenosa para Hemodiálise", "30609060"),
        ("Trombectomia Venosa", "30609070"),
        ("Embolectomia Arterial", "30609071"),
        ("Amputação de Membro Inferior", "30609080"),
        ("Implante de Filtro de Veia Cava", "30609090"),
    ],
    "Cirurgia de Cabeça e Pescoço": [
        ("Tireoidectomia Total", "30701010"),
        ("Paratireoidectomia", "30701011"),
        ("Esvaziamento Cervical Radical", "30701020"),
        ("Esvaziamento Cervical Seletivo", "30701021"),
        ("Parotidectomia", "30701030"),
        ("Submandibulectomia", "30701031"),
        ("Glossectomia Parcial", "30701040"),
        ("Laringectomia Total", "30701050"),
        ("Laringectomia Parcial", "30701051"),
        ("Mandibulectomia Segmentar com Reconstrução", "30701060"),
        ("Maxilectomia", "30701061"),
    ],
    "Cirurgia Pediátrica": [
        ("Herniorrafia Inguinal Pediátrica", "30702010"),
        ("Orquidopexia", "30702020"),
        ("Piloromiotomia (Estenose Hipertrófica do Piloro)", "30702030"),
        ("Correção de Refluxo Vesicoureteral", "30702040"),
        ("Correção de Hérnia Diafragmática Congênita", "30702050"),
        ("Correção de Atresia de Esôfago", "30702060"),
        ("Correção de Onfalocele / Gastrosquise", "30702070"),
        ("Pull-Through para Doença de Hirschsprung", "30702080"),
        ("Correção de Malformação Anorretal", "30702090"),
        ("Esplenectomia Pediátrica (Laparoscópica)", "30702100"),
    ],
    "Neurocirurgia": [
        ("Craniotomia para Ressecção de Tumor Cerebral", "30801010"),
        ("Microdiscectomia Lombar", "30801020"),
        ("Artrodese de Coluna (Neurocirurgia)", "30801021"),
        ("Laminectomia Descompressiva", "30801022"),
        ("Clipagem de Aneurisma Cerebral", "30801030"),
        ("Embolização de Aneurisma Cerebral", "30801031"),
        ("Derivação Ventrículo-Peritoneal (DVP)", "30801040"),
        ("Craniectomia Descompressiva", "30801050"),
        ("Implante de Estimulador Cerebral Profundo (DBS)", "30801060"),
        ("Radiocirurgia Estereotáxica (Gamma Knife)", "30801070"),
        ("Cirurgia de Epilepsia (Lobectomia Temporal)", "30801080"),
        ("Ressecção de Tumor de Base de Crânio", "30801090"),
        ("Cirurgia de Malformação Arteriovenosa (MAV)", "30801100"),
        ("Descompressão Microvascular (Nervo Trigêmeo)", "30801110"),
        ("Implante de Bomba de Baclofeno", "30801120"),
    ],
    "Dermatologia": [
        ("Exérese de Nevo / Lesão de Pele", "30203018"),
        ("Biópsia de Pele (Incisional/Excisional)", "30203050"),
        ("Crioterapia de Lesões Cutâneas", "30203077"),
        ("Eletrocoagulação / Cauterização", "30203078"),
        ("Cirurgia Micrográfica de Mohs", "30203079"),
        ("Peeling Químico", "30203034"),
        ("Laserterapia Cutânea (CO2, Nd:YAG)", "30203085"),
        ("Fototerapia UVB / PUVA", "30203086"),
        ("Preenchimento com Ácido Hialurônico", "30203087"),
        ("Aplicação de Toxina Botulínica (Estético)", "30203088"),
        ("Dermatoscopia Digital / Mapeamento de Nevos", "30203089"),
        ("Infiltração Intralesional de Corticoide", "30203026"),
        ("Curetagem e Eletrodissecção", "30203090"),
        ("Tratamento de Queloides", "30203091"),
        ("Microagulhamento", "30203092"),
    ],
    "Ginecologia e Obstetrícia": [
        ("Histeroscopia Diagnóstica", "31309038"),
        ("Histeroscopia Cirúrgica (Polipectomia/Miomectomia)", "31309039"),
        ("Laparoscopia Ginecológica Diagnóstica", "31309054"),
        ("Laparoscopia Cirúrgica (Endometriose/Cistos)", "31309055"),
        ("Colposcopia com Biópsia", "31309011"),
        ("Conização do Colo Uterino (CAF/Clássica)", "31309046"),
        ("Histerectomia Laparoscópica Total", "31310015"),
        ("Histerectomia Vaginal", "31310016"),
        ("Curetagem Uterina Semiótica", "31309020"),
        ("Miomectomia Laparoscópica", "31309060"),
        ("Salpingectomia / Ooforectomia Laparoscópica", "31309061"),
        ("Cerclagem Cervical", "31310020"),
        ("Cesariana", "31310030"),
        ("Parto Normal Assistido", "31310031"),
        ("Fertilização In Vitro (FIV)", "31309070"),
        ("Inseminação Intrauterina (IIU)", "31309071"),
    ],
    "Pediatria": [
        ("Consulta Pediátrica de Rotina / Puericultura", "10101012"),
        ("Teste do Pezinho Ampliado", "40309085"),
        ("Triagem Neonatal Completa", "40309093"),
        ("Avaliação do Desenvolvimento Neuropsicomotor", "10101020"),
        ("Imunização / Vacinação", "30101010"),
        ("Teste da Orelhinha (Emissões Otoacústicas)", "40309094"),
        ("Teste do Olhinho (Teste do Reflexo Vermelho)", "40309095"),
        ("Teste do Coraçãozinho (Oximetria de Pulso)", "40309096"),
        ("Avaliação Nutricional Pediátrica", "10101039"),
        ("Consulta de Acompanhamento de Asma Infantil", "10101040"),
        ("Consulta de Alergia Alimentar Pediátrica", "10101041"),
    ],
    "Neurologia": [
        ("Eletroencefalograma (EEG)", "40601056"),
        ("Eletroneuromiografia (ENMG)", "40601072"),
        ("Punção Lombar Diagnóstica", "30601020"),
        ("Aplicação de Toxina Botulínica Terapêutica", "30601070"),
        ("Potencial Evocado (Visual/Auditivo/Somatossensitivo)", "40601064"),
        ("Polissonografia", "40601080"),
        ("Teste de Latências Múltiplas do Sono", "40601081"),
        ("Doppler Transcraniano", "40601082"),
        ("Monitorização por Vídeo-EEG", "40601083"),
        ("Trombólise Endovenosa (rt-PA) para AVC", "30601090"),
        ("Teste Neuropsicológico Computadorizado", "40601084"),
        ("Bloqueio Anestésico de Nervo Periférico", "30601100"),
    ],
    "Oftalmologia": [
        ("Facoemulsificação com Implante de LIO (Catarata)", "30501050"),
        ("Fotocoagulação a Laser da Retina", "30501069"),
        ("Injeção Intravítrea de Anti-VEGF", "30501107"),
        ("Vitrectomia Posterior", "30501085"),
        ("Trabeculoplastia Seletiva a Laser (SLT)", "30501077"),
        ("Trabeculectomia (Cirurgia de Glaucoma)", "30501078"),
        ("Implante de Válvula para Glaucoma", "30501079"),
        ("Ceratoplastia Penetrante (Transplante de Córnea)", "30501093"),
        ("Cross-Linking Corneano", "30501094"),
        ("Cirurgia Refrativa (LASIK/PRK)", "30501095"),
        ("Blefaroplastia Funcional", "30501115"),
        ("Correção de Estrabismo", "30501120"),
        ("Cirurgia de Descolamento de Retina (Introflexão Escleral)", "30501130"),
        ("Retinopexia Pneumática", "30501131"),
        ("Capsulotomia YAG Laser", "30501140"),
    ],
    "Urologia": [
        ("Prostatectomia Radical Laparoscópica/Robótica", "31004027"),
        ("Ressecção Transuretral de Próstata (RTU-P)", "31004019"),
        ("Litotripsia Extracorpórea (LECO)", "31003011"),
        ("Ureteroscopia Flexível com Laser (Litíase)", "31003012"),
        ("Nefrolitotomia Percutânea", "31003013"),
        ("Nefrectomia Radical Laparoscópica", "31001069"),
        ("Nefrectomia Parcial Laparoscópica/Robótica", "31001070"),
        ("Vasectomia", "31006015"),
        ("Reversão de Vasectomia (Vasovasostomia)", "31006016"),
        ("Cistoscopia Diagnóstica", "31003020"),
        ("Ressecção Transuretral de Bexiga (RTU-B)", "31003030"),
        ("Implante de Esfíncter Urinário Artificial", "31004030"),
        ("Implante de Prótese Peniana", "31006020"),
        ("Sling Masculino/Feminino para Incontinência", "31004031"),
        ("Orquiectomia", "31006030"),
    ],
    "Psiquiatria": [
        ("Consulta Psiquiátrica Inicial", "10101071"),
        ("Consulta Psiquiátrica de Seguimento", "10101072"),
        ("Psicoterapia de Apoio", "10101098"),
        ("Avaliação Neuropsicológica Completa", "40801068"),
        ("Eletroconvulsoterapia (ECT)", "30805012"),
        ("Estimulação Magnética Transcraniana (EMT)", "30805013"),
        ("Avaliação Psiquiátrica Forense / Pericial", "10101080"),
        ("Entrevista Diagnóstica Estruturada (MINI/SCID)", "10101081"),
        ("Manejo de Crise Psiquiátrica", "10101082"),
        ("Internação Psiquiátrica (Avaliação para)", "10101083"),
        ("Avaliação de Dependência Química", "10101084"),
    ],
    "Oncologia Clínica": [
        ("Quimioterapia Antineoplásica (Sessão)", "30724537"),
        ("Imunoterapia Oncológica (Sessão)", "90020030"),
        ("Terapia Alvo Molecular (Sessão)", "90020056"),
        ("Hormonioterapia", "90020048"),
        ("Punção de Medula Óssea (Mielograma)", "40204014"),
        ("Biópsia de Tumor Guiada por TC/US", "32016013"),
        ("Quimioterapia Intratecal", "30724538"),
        ("Consulta Oncológica para Estadiamento", "10101090"),
        ("Avaliação para Cuidados Paliativos", "10101091"),
        ("PET-CT para Estadiamento", "41001200"),
        ("Biópsia Líquida (ctDNA)", "90020070"),
        ("Teste de Perfil Genômico Tumoral", "90020071"),
    ],
    "Endocrinologia e Metabologia": [
        ("Punção Aspirativa de Tireoide Guiada por US (PAAF)", "32012017"),
        ("Teste de Supressão com Dexametasona", "40302210"),
        ("Teste Oral de Tolerância à Glicose (TOTG)", "40302228"),
        ("Densitometria Óssea (DXA)", "40901141"),
        ("Monitorização Contínua de Glicose (CGM)", "40302230"),
        ("Implante Subcutâneo de Hormônio", "20104037"),
        ("Teste de Estímulo com GnRH", "40302235"),
        ("Ultrassonografia de Tireoide", "40901140"),
        ("Teste de Estímulo com ACTH", "40302236"),
        ("Avaliação de Composição Corporal (Bioimpedância/DXA)", "40901142"),
        ("Curva de Insulina", "40302237"),
    ],
    "Gastroenterologia": [
        ("Endoscopia Digestiva Alta", "40201028"),
        ("Colonoscopia", "40201036"),
        ("Polipectomia Endoscópica", "40201044"),
        ("Cápsula Endoscópica", "40201052"),
        ("Ligadura Elástica de Varizes Esofagianas", "40201060"),
        ("CPRE (Colangiopancreatografia Retrógrada Endoscópica)", "40201079"),
        ("Manometria Esofágica de Alta Resolução", "40201087"),
        ("pHmetria Esofágica 24h / Impedanciometria", "40201088"),
        ("Ecoendoscopia (Ultrassom Endoscópico)", "40201089"),
        ("Mucosectomia Endoscópica (EMR)", "40201090"),
        ("Dissecção Endoscópica de Submucosa (ESD)", "40201091"),
        ("Elastografia Hepática Transitória (FibroScan)", "40201092"),
        ("Biópsia Hepática Percutânea", "40201093"),
        ("Dilatação Endoscópica de Estenose", "40201094"),
    ],
    "Otorrinolaringologia": [
        ("Timpanoplastia", "30401034"),
        ("Estapedotomia / Estapedectomia", "30401035"),
        ("Septoplastia", "30404012"),
        ("Adenoamigdalectomia", "30403019"),
        ("Cirurgia Endoscópica Funcional dos Seios (FESS)", "30404020"),
        ("Implante Coclear", "30401042"),
        ("Audiometria Tonal e Vocal", "40601099"),
        ("Impedanciometria / Timpanometria", "40601100"),
        ("Rinoplastia Funcional", "30404039"),
        ("Microcirurgia de Laringe", "30403030"),
        ("Tireoplastia / Injeção de Prega Vocal", "30403031"),
        ("Polissonografia (ORL — Apneia)", "40601101"),
        ("Uvulopalatofaringoplastia (UPPP)", "30403040"),
        ("Videonasolaringoscopia", "40601102"),
        ("BERA (Potencial Evocado Auditivo)", "40601103"),
    ],
    "Anestesiologia": [
        ("Anestesia Geral (Porte Médio)", "30901010"),
        ("Anestesia Geral (Grande Porte)", "30901011"),
        ("Raquianestesia", "30901020"),
        ("Peridural Lombar", "30901021"),
        ("Bloqueio de Plexo Braquial", "30901030"),
        ("Bloqueio de Nervo Periférico Guiado por Ultrassom", "30901031"),
        ("Sedação para Procedimento Endoscópico", "30901040"),
        ("Analgesia Pós-Operatória com Cateter Peridural", "30901050"),
        ("Bloqueio do Plano Transverso do Abdome (TAP Block)", "30901032"),
        ("Bloqueio do Nervo Femoral / Adutores", "30901033"),
        ("Anestesia para Cirurgia Cardíaca", "30901060"),
        ("Anestesia para Cesariana", "30901070"),
    ],
    "Medicina do Esporte": [
        ("Consulta em Medicina do Esporte", "10101100"),
        ("Teste Ergoespirométrico (VO2 Max)", "40302250"),
        ("Avaliação Isocinética", "40302251"),
        ("Infiltração Articular Guiada por US", "30901100"),
        ("Teste de Aptidão Física", "40302252"),
        ("Avaliação de Composição Corporal", "40302253"),
        ("Viscossuplementação (Ácido Hialurônico Articular)", "30901101"),
        ("Terapia por Ondas de Choque (ESWT)", "30901102"),
        ("Infiltração com PRP (Plasma Rico em Plaquetas)", "30901103"),
    ],
    "Geriatria e Gerontologia": [
        ("Avaliação Geriátrica Ampla (AGA)", "10101110"),
        ("Avaliação Cognitiva (Mini-Exame do Estado Mental)", "10101111"),
        ("Avaliação Funcional (Katz / Lawton)", "10101112"),
        ("Avaliação de Risco de Quedas", "10101113"),
        ("Revisão de Polifarmácia / Desprescrição", "10101114"),
        ("Avaliação Nutricional do Idoso (MNA)", "10101115"),
        ("Consulta de Cuidados Paliativos", "10101116"),
        ("Teste do Relógio", "10101117"),
        ("Avaliação de Fragilidade (Fried)", "10101118"),
    ],
    "Reumatologia": [
        ("Consulta Reumatológica", "10101120"),
        ("Infiltração Articular (Corticoide)", "30901110"),
        ("Capilaroscopia Periungueal", "40601110"),
        ("Densitometria Óssea (DXA)", "40901141"),
        ("Biópsia Sinovial", "30901111"),
        ("Artrocentese Diagnóstica", "30901112"),
        ("Ultrassonografia Musculoesquelética", "40901150"),
        ("Infiltração com Ácido Hialurônico", "30901113"),
        ("Aplicação de Imunobiológico (Infusão)", "90020080"),
        ("Bloqueio de Nervo Periférico para Dor", "30901114"),
    ],
    "Pneumologia": [
        ("Espirometria", "40302300"),
        ("Prova de Função Pulmonar Completa", "40302301"),
        ("Broncoscopia Flexível", "40201100"),
        ("Broncoscopia com Lavado Broncoalveolar (LBA)", "40201101"),
        ("Biópsia Transbrônquica", "40201102"),
        ("Teste de Broncoprovocação com Metacolina", "40302302"),
        ("Polissonografia (Pneumologia — Apneia do Sono)", "40601080"),
        ("Titulação de CPAP/BiPAP", "40601085"),
        ("Prova de Caminhada de 6 Minutos (TC6M)", "40302303"),
        ("Teste de Difusão do CO (DLCO)", "40302304"),
        ("Gasometria Arterial", "40302305"),
        ("Toracocentese Diagnóstica/Terapêutica", "30608035"),
    ],
    "Nefrologia": [
        ("Consulta Nefrológica", "10101130"),
        ("Sessão de Hemodiálise", "31501010"),
        ("Implante de Cateter de Hemodiálise", "31501020"),
        ("Biópsia Renal Percutânea", "31501030"),
        ("Diálise Peritoneal (Implante de Cateter)", "31501040"),
        ("Plasmaférese Terapêutica", "31501050"),
        ("Avaliação Pré-Transplante Renal", "10101131"),
        ("Acompanhamento Pós-Transplante Renal", "10101132"),
        ("Ultrassonografia Renal com Doppler", "40901160"),
    ],
    "Hematologia e Hemoterapia": [
        ("Mielograma (Punção de Medula Óssea)", "40204014"),
        ("Biópsia de Medula Óssea", "40204015"),
        ("Imunofenotipagem por Citometria de Fluxo", "40204016"),
        ("Quimioterapia para Leucemia/Linfoma", "30724540"),
        ("Transplante Autólogo de Medula Óssea", "30724541"),
        ("Transplante Alogênico de Medula Óssea", "30724542"),
        ("Transfusão de Hemocomponentes", "40204020"),
        ("Aférese Terapêutica", "40204021"),
        ("Avaliação de Distúrbios de Coagulação", "10101140"),
        ("Teste de Anticoagulação (INR/TTPa)", "40302310"),
    ],
    "Infectologia": [
        ("Consulta Infectológica", "10101150"),
        ("Manejo de HIV/AIDS (Consulta TARV)", "10101151"),
        ("Avaliação de Infecção Hospitalar (CCIH)", "10101152"),
        ("Manejo de Hepatite B e C", "10101153"),
        ("Avaliação Pré-Viagem (Medicina do Viajante)", "10101154"),
        ("Teste Rápido para HIV/Sífilis/Hepatites", "40302320"),
        ("Avaliação de Infecção em Transplantados", "10101155"),
        ("Manejo de Tuberculose Multirresistente", "10101156"),
        ("Consulta de Profilaxia Pós-Exposição (PEP/PrEP)", "10101157"),
    ],
    "Medicina Intensiva": [
        ("Intubação Orotraqueal e Ventilação Mecânica", "31001010"),
        ("Acesso Venoso Central (Passagem de Cateter)", "31001011"),
        ("Monitorização Hemodinâmica Invasiva", "31001012"),
        ("Traqueostomia à Beira do Leito", "31001013"),
        ("Drenagem de Tórax à Beira do Leito", "31001014"),
        ("Diálise Contínua (CRRT) na UTI", "31001015"),
        ("Manejo de Sepse / Choque Séptico", "31001016"),
        ("Broncoscopia à Beira do Leito", "31001017"),
        ("Ultrassonografia Point-of-Care (POCUS)", "31001018"),
        ("Implante de ECMO na UTI", "31001019"),
    ],
    "Radiologia e Diagnóstico por Imagem": [
        ("Tomografia Computadorizada de Crânio", "41001010"),
        ("Tomografia Computadorizada de Tórax", "41001011"),
        ("Tomografia Computadorizada de Abdome", "41001012"),
        ("Ressonância Magnética de Encéfalo", "41001020"),
        ("Ressonância Magnética de Coluna", "41001021"),
        ("Ressonância Magnética de Joelho", "41001022"),
        ("Ressonância Magnética de Ombro", "41001023"),
        ("Ultrassonografia de Abdome Total", "40901010"),
        ("Ultrassonografia Obstétrica", "40901011"),
        ("Mamografia Digital", "40901020"),
        ("Densitometria Óssea", "40901141"),
        ("Angiotomografia de Aorta", "41001030"),
        ("Biópsia Percutânea Guiada por TC/US", "41001040"),
    ],
    "Medicina Nuclear": [
        ("PET-CT com 18F-FDG", "41001200"),
        ("Cintilografia Miocárdica (Perfusão)", "41002010"),
        ("Cintilografia Óssea", "41002020"),
        ("Cintilografia de Tireoide", "41002030"),
        ("Cintilografia Renal (DMSA/DTPA)", "41002040"),
        ("Cintilografia Pulmonar (Ventilação/Perfusão)", "41002050"),
        ("Terapia com Iodo Radioativo (131-I)", "41002060"),
        ("PET-CT com PSMA (Próstata)", "41001201"),
        ("Terapia com Lutécio-177 (PSMA / DOTATATE)", "41002070"),
    ],
    "Patologia / Anatomia Patológica": [
        ("Exame Anatomopatológico de Peça Cirúrgica (Pequena)", "40501010"),
        ("Exame Anatomopatológico de Peça Cirúrgica (Grande)", "40501011"),
        ("Citopatologia Oncótica Cervicovaginal (Papanicolaou)", "40501020"),
        ("Citopatologia de Punção (PAAF)", "40501021"),
        ("Imuno-histoquímica (por anticorpo)", "40501030"),
        ("Biópsia por Congelação (Intraoperatória)", "40501040"),
        ("Hibridização In Situ (FISH/CISH)", "40501050"),
        ("Patologia Molecular / Sequenciamento", "40501060"),
        ("Revisão de Lâminas", "40501070"),
    ],
    "Medicina de Família e Comunidade": [
        ("Consulta de Atenção Primária", "10101160"),
        ("Consulta de Pré-Natal de Baixo Risco", "10101161"),
        ("Consulta de Puericultura (APS)", "10101162"),
        ("Rastreamento de Câncer (Coleta de Papanicolaou)", "10101163"),
        ("Consulta de Saúde Mental (APS)", "10101164"),
        ("Consulta de Doenças Crônicas (HAS/DM)", "10101165"),
        ("Visita Domiciliar", "10101166"),
        ("Procedimentos Menores (Sutura, Drenagem de Abscesso)", "10101167"),
        ("Eletrocardiograma na APS", "40301010"),
    ],
    "Mastologia": [
        ("Consulta Mastológica", "10101170"),
        ("Core Biopsy de Mama Guiada por US", "40901030"),
        ("Mamotomia (Biópsia a Vácuo)", "40901031"),
        ("Mastectomia Radical Modificada", "30308080"),
        ("Quadrantectomia / Setorectomia", "30308081"),
        ("Pesquisa de Linfonodo Sentinela", "30308082"),
        ("Esvaziamento Axilar", "30308083"),
        ("Reconstrução Mamária Imediata", "30308084"),
        ("Cirurgia Oncoplástica da Mama", "30308085"),
        ("Biópsia Excisional de Nódulo Mamário", "30308086"),
        ("Mamografia de Rastreamento", "40901020"),
        ("Ressonância Magnética das Mamas", "41001025"),
    ],
    "Nutrologia": [
        ("Consulta Nutrológica", "10101180"),
        ("Avaliação de Composição Corporal (Bioimpedância)", "40302340"),
        ("Avaliação Metabólica Completa", "40302341"),
        ("Calorimetria Indireta", "40302342"),
        ("Implante Hormonal Subcutâneo", "20104037"),
        ("Prescrição de Nutrição Parenteral", "40302343"),
        ("Prescrição de Nutrição Enteral", "40302344"),
        ("Avaliação Pré-Bariátrica", "10101181"),
        ("Acompanhamento Pós-Bariátrico", "10101182"),
    ],
    "Acupuntura": [
        ("Sessão de Acupuntura Sistêmica", "50000470"),
        ("Sessão de Eletroacupuntura", "50000471"),
        ("Sessão de Auriculoterapia", "50000472"),
        ("Moxabustão", "50000473"),
        ("Ventosaterapia", "50000474"),
        ("Acupuntura Craniana", "50000475"),
        ("Acupuntura para Dor Crônica", "50000476"),
        ("Acupuntura Obstétrica", "50000477"),
    ],
    "Medicina do Trabalho": [
        ("Exame Admissional", "10101190"),
        ("Exame Demissional", "10101191"),
        ("Exame Periódico", "10101192"),
        ("Exame de Retorno ao Trabalho", "10101193"),
        ("Exame de Mudança de Função", "10101194"),
        ("Avaliação Ergonômica do Trabalho", "10101195"),
        ("Audiometria Ocupacional", "40601099"),
        ("Espirometria Ocupacional", "40302300"),
        ("Avaliação de Nexo Causal", "10101196"),
    ],
    "Medicina Legal e Perícia Médica": [
        ("Exame de Corpo de Delito", "10101200"),
        ("Perícia para Nexo Causal (Previdenciário)", "10101201"),
        ("Avaliação de Sanidade Mental", "10101202"),
        ("Avaliação de Incapacidade Laborativa", "10101203"),
        ("Exame de Conjunção Carnal", "10101204"),
        ("Exame Necroscópico (Necropsia)", "10101205"),
        ("Laudo Pericial Cível / Criminal", "10101206"),
        ("Avaliação de Dano Corporal", "10101207"),
    ],
    "Medicina Física e Reabilitação (Fisiatria)": [
        ("Consulta em Fisiatria", "10101210"),
        ("Eletroneuromiografia (ENMG) Diagnóstica", "40601072"),
        ("Infiltração de Ponto-Gatilho", "30901120"),
        ("Bloqueio Articular Guiado por US", "30901121"),
        ("Aplicação de Toxina Botulínica para Espasticidade", "30601070"),
        ("Prescrição de Órteses e Próteses", "10101211"),
        ("Avaliação Funcional para Reabilitação", "10101212"),
        ("Ondas de Choque para Tendinopatias", "30901122"),
        ("Agulhamento Seco / Dry Needling", "30901123"),
        ("Viscossuplementação Articular", "30901124"),
    ],
    "Genética Médica": [
        ("Consulta em Genética Médica", "10101220"),
        ("Aconselhamento Genético Pré-Natal", "10101221"),
        ("Cariótipo (Citogenética Convencional)", "40204030"),
        ("Microarray Cromossômico (CGH-Array)", "40204031"),
        ("Sequenciamento de Exoma", "40204032"),
        ("Sequenciamento de Genoma Completo", "40204033"),
        ("Painel Genético Direcionado (NGS)", "40204034"),
        ("Teste Genético Pré-Implantação (PGT)", "40204035"),
        ("MLPA para Deleções/Duplicações", "40204036"),
    ],
    "Cirurgia do Aparelho Digestivo": [
        ("Esofagectomia (Transtorácica / Transhiatal)", "30606300"),
        ("Gastrectomia Oncológica (D2)", "30606301"),
        ("Duodenopancreatectomia (Whipple)", "30606302"),
        ("Pancreatectomia Distal (Corpo-Caudal)", "30606303"),
        ("Hepatectomia (Ressecção Hepática)", "30606304"),
        ("Bypass Gástrico em Y de Roux", "30606200"),
        ("Sleeve Gastrectomy (Gastrectomia Vertical)", "30606201"),
        ("Colecistectomia Laparoscópica", "30606123"),
        ("Derivação Biliodigestiva", "30606305"),
        ("Hernioplastia Hiatal Laparoscópica", "30606306"),
        ("Transplante Hepático", "30606310"),
    ],
    "Coloproctologia": [
        ("Colonoscopia Diagnóstica e Terapêutica", "40201036"),
        ("Hemorroidectomia (Milligan-Morgan / Ferguson)", "30607250"),
        ("Fistulotomia / Fistulectomia Anal", "30607251"),
        ("Esfincteroplastia Anal", "30607252"),
        ("Colectomia Total com Bolsa Ileal (IPAA)", "30607260"),
        ("Retossigmoidectomia Laparoscópica", "30607261"),
        ("Colectomia Direita (Hemicolectomia)", "30607262"),
        ("Manometria Anorretal", "40201095"),
        ("Ligadura Elástica de Hemorroidas", "30607253"),
        ("THD (Desarterialização Hemorroidária Transanal)", "30607254"),
        ("Cirurgia de Prolapso Retal", "30607270"),
    ],
    "Angiologia": [
        ("Consulta Angiológica", "10101230"),
        ("Eco-Doppler Venoso de Membros Inferiores", "40901170"),
        ("Eco-Doppler Arterial de Membros Inferiores", "40901171"),
        ("Eco-Doppler de Carótidas e Vertebrais", "40901172"),
        ("Escleroterapia de Telangiectasias", "30609052"),
        ("Escleroterapia com Espuma (Varizes)", "30609053"),
        ("Índice Tornozelo-Braquial (ITB)", "40901173"),
        ("Avaliação de Linfedema", "10101231"),
        ("Pletismografia Venosa", "40901174"),
    ],
    "Alergia e Imunologia": [
        ("Teste Cutâneo de Leitura Imediata (Prick Test)", "40302350"),
        ("Teste de Provocação Oral (Alergia Alimentar)", "40302351"),
        ("Imunoterapia Subcutânea (Dessensibilização)", "30901130"),
        ("Imunoterapia Sublingual", "30901131"),
        ("Teste de Contato (Patch Test)", "40302352"),
        ("Espirometria para Asma", "40302300"),
        ("Dosagem de IgE Específica", "40302353"),
        ("Avaliação de Imunodeficiência", "10101240"),
        ("Infusão de Imunoglobulina Endovenosa", "90020090"),
    ],
    "Radioterapia": [
        ("Radioterapia Conformacional 3D (Planejamento + Sessões)", "41003010"),
        ("Radioterapia de Intensidade Modulada (IMRT)", "41003011"),
        ("Radiocirurgia Estereotáxica Craniana", "41003020"),
        ("Radioterapia Corporal Estereotáxica (SBRT)", "41003021"),
        ("Braquiterapia de Alta Taxa de Dose", "41003030"),
        ("Braquiterapia de Baixa Taxa de Dose", "41003031"),
        ("Radioterapia Intraoperatória", "41003040"),
        ("Irradiação Total do Corpo (TBI)", "41003050"),
        ("Planejamento com PET-CT para Radioterapia", "41003060"),
    ],
    "Medicina de Emergência": [
        ("Atendimento de Emergência (Sala Vermelha)", "10101250"),
        ("Intubação de Sequência Rápida", "31001010"),
        ("Drenagem de Pneumotórax", "30608030"),
        ("Cardioversão Elétrica de Emergência", "30607160"),
        ("Redução de Fratura / Luxação", "30724200"),
        ("Sutura de Ferimento Complexo", "30203100"),
        ("Ultrassonografia FAST (Trauma)", "40901180"),
        ("Acesso Intraósseo", "31001020"),
        ("Pericardiocentese de Emergência", "30607152"),
        ("Toracotomia de Reanimação", "30608070"),
    ],
    "Cirurgia da Mão": [
        ("Liberação do Túnel do Carpo", "30730010"),
        ("Reparo de Tendões Flexores", "30730020"),
        ("Reparo de Tendões Extensores", "30730021"),
        ("Neurorrafia (Reparo de Nervo Periférico)", "30730030"),
        ("Osteossíntese de Fratura de Falanges/Metacarpos", "30730040"),
        ("Transferência Tendinosa", "30730050"),
        ("Fasciotomia para Contratura de Dupuytren", "30730060"),
        ("Reimplante de Dedo Amputado", "30730070"),
        ("Artrodese de Articulação da Mão/Punho", "30730080"),
        ("Liberação do Dedo em Gatilho", "30730090"),
    ],
    "Homeopatia": [
        ("Consulta Homeopática Inicial", "10101260"),
        ("Consulta Homeopática de Retorno", "10101261"),
        ("Repertorização Homeopática", "10101262"),
        ("Avaliação Homeopática Pediátrica", "10101263"),
    ],
    "Medicina Preventiva e Social": [
        ("Avaliação Epidemiológica", "10101270"),
        ("Check-up Preventivo", "10101271"),
        ("Consulta de Medicina Preventiva", "10101272"),
        ("Avaliação de Risco Cardiovascular", "10101273"),
        ("Rastreamento Populacional (Programa)", "10101274"),
    ],
}


# ===========================================================================
# 3. HOSPITAIS_POR_CIDADE
#    20 cidades brasileiras com hospitais REAIS (8-12 por cidade).
#    Formato: { "Cidade": ("UF", [lista de hospitais]) }
# ===========================================================================

HOSPITAIS_POR_CIDADE = {
    "São Paulo": ("SP", [
        "Hospital Israelita Albert Einstein",
        "Hospital Sírio-Libanês",
        "Hospital das Clínicas da FMUSP (HC-FMUSP)",
        "Hospital Santa Catarina — Paulista",
        "Hospital 9 de Julho",
        "Hospital Alemão Oswaldo Cruz",
        "Hospital Samaritano Higienópolis",
        "Hospital São Luiz — Itaim",
        "Hospital São Luiz — Morumbi",
        "Hospital São Luiz — Jabaquara",
        "Hospital Beneficência Portuguesa de São Paulo",
        "A.C. Camargo Cancer Center",
        "Hospital do Coração (HCor)",
        "Instituto do Câncer do Estado de São Paulo (ICESP)",
        "Hospital BP — Mirante",
        "Hospital Santa Marcelina",
        "Hospital Infantil Sabará",
        "Hospital Paulistano",
    ]),
    "Rio de Janeiro": ("RJ", [
        "Hospital Copa D'Or",
        "Hospital Barra D'Or",
        "Hospital Samaritano Botafogo",
        "Hospital Pró-Cardíaco",
        "Hospital Quinta D'Or",
        "Hospital Américas (Barra da Tijuca)",
        "Hospital Glória D'Or",
        "Instituto Nacional do Câncer (INCA)",
        "Hospital Federal de Bonsucesso",
        "Hospital Copa Star",
        "Hospital São Lucas Copacabana",
        "Hospital Vitória (Barra da Tijuca)",
    ]),
    "Belo Horizonte": ("MG", [
        "Hospital Mater Dei — Santo Agostinho",
        "Hospital Mater Dei — Contorno",
        "Hospital Lifecenter",
        "Hospital Vera Cruz",
        "Hospital Felício Rocho",
        "Hospital Biocor",
        "Hospital das Clínicas da UFMG",
        "Santa Casa de Belo Horizonte",
        "Hospital Vila da Serra",
        "Hospital Belo Horizonte",
        "Hospital Madre Teresa",
    ]),
    "Curitiba": ("PR", [
        "Hospital Pequeno Príncipe",
        "Hospital Nossa Senhora das Graças",
        "Hospital Universitário Cajuru (PUCPR)",
        "Hospital Marcelino Champagnat",
        "Hospital Cruz Vermelha — Curitiba",
        "Hospital Santa Cruz — Curitiba",
        "Hospital Erasto Gaertner (Oncologia)",
        "Hospital IPO — Instituto Paranaense de Otorrinolaringologia",
        "Hospital do Trabalhador",
        "Hospital de Clínicas da UFPR (HC-UFPR)",
    ]),
    "Porto Alegre": ("RS", [
        "Hospital Moinhos de Vento",
        "Hospital São Lucas da PUCRS",
        "Hospital de Clínicas de Porto Alegre (HCPA)",
        "Hospital Nossa Senhora da Conceição",
        "Hospital Ernesto Dornelles",
        "Santa Casa de Misericórdia de Porto Alegre",
        "Hospital Divina Providência",
        "Hospital da Criança Santo Antônio",
        "Hospital Presidente Vargas",
        "Hospital Fêmina",
    ]),
    "Salvador": ("BA", [
        "Hospital Santa Izabel",
        "Hospital Português — Salvador",
        "Hospital da Bahia (HBA)",
        "Hospital Aliança",
        "Hospital Aristides Maltez (Liga Baiana Contra o Câncer)",
        "Hospital Universitário Prof. Edgard Santos (HUPES/UFBA)",
        "Hospital São Rafael",
        "Hospital Jorge Valente",
        "Hospital Cardio Pulmonar",
        "Hospital Roberto Santos",
    ]),
    "Brasília": ("DF", [
        "Hospital Santa Lúcia — Asa Sul",
        "Hospital Santa Lúcia — Norte",
        "Hospital Sírio-Libanês — Brasília",
        "Hospital Anchieta",
        "Hospital DF Star",
        "Hospital Brasília",
        "Hospital Regional da Asa Norte (HRAN)",
        "Hospital de Base do Distrito Federal (HBDF)",
        "Hospital Santa Marta",
        "Hospital Daher",
        "Hospital Santa Helena — Brasília",
    ]),
    "Recife": ("PE", [
        "Real Hospital Português",
        "Hospital Esperança — Recife",
        "Hospital da Restauração",
        "Hospital Santa Joana — Recife",
        "Hospital Universitário Oswaldo Cruz (HUOC)",
        "Hospital Memorial São José",
        "Hospital Albert Sabin — Recife",
        "Hospital Jayme da Fonte",
        "Instituto de Medicina Integral Prof. Fernando Figueira (IMIP)",
        "Hospital Português — Recife",
    ]),
    "Fortaleza": ("CE", [
        "Hospital Geral de Fortaleza (HGF)",
        "Hospital de Messejana Dr. Carlos Alberto Studart Gomes",
        "Hospital Universitário Walter Cantídio (HUWC/UFC)",
        "Instituto do Câncer do Ceará (ICC)",
        "Hospital Unimed Fortaleza",
        "Hospital São Carlos — Fortaleza",
        "Hospital Monte Klinikum",
        "Hospital São Mateus — Fortaleza",
        "Hospital Regional Unimed",
        "Hospital e Maternidade São Luiz — Fortaleza",
    ]),
    "Goiânia": ("GO", [
        "Hospital Araújo Jorge (Associação de Combate ao Câncer)",
        "Hospital das Clínicas da UFG (HC-UFG)",
        "Hospital Encore — Goiânia",
        "Hospital Santa Helena — Goiânia",
        "Hospital Ortopédico de Goiânia",
        "Hospital do Coração de Goiás (Anis Rassi)",
        "Hospital Alberto Rassi (HGG)",
        "Hospital e Maternidade Amparo",
        "Hospital São Salvador",
    ]),
    "Manaus": ("AM", [
        "Hospital Adventista de Manaus",
        "Hospital Checkup",
        "Hospital Universitário Getúlio Vargas (HUGV/UFAM)",
        "Fundação Hospital Adriano Jorge",
        "Hospital e Pronto-Socorro 28 de Agosto",
        "Hospital Beneficente Portuguesa de Manaus",
        "Fundação Centro de Controle de Oncologia do Amazonas (FCECON)",
        "Hospital Samel",
        "Hospital Santa Júlia — Manaus",
    ]),
    "Belém": ("PA", [
        "Hospital Ophir Loyola",
        "Hospital Porto Dias",
        "Hospital Universitário João de Barros Barreto (HUJBB/UFPA)",
        "Hospital de Clínicas Gaspar Vianna",
        "Hospital Amazônia",
        "Hospital Adventista de Belém",
        "Hospital Ordem Terceira",
        "Hospital Saúde da Mulher",
        "Santa Casa de Misericórdia do Pará",
    ]),
    "Campinas": ("SP", [
        "Hospital PUC-Campinas",
        "Hospital e Maternidade Celso Pierro",
        "Hospital de Clínicas da Unicamp (HC-Unicamp)",
        "Hospital Vera Cruz — Campinas",
        "Hospital Municipal Dr. Mário Gatti",
        "Hospital Centro Médico — Campinas",
        "Hospital Samaritano — Campinas",
        "Hospital Madre Theodora — Campinas",
        "Hospital Metropolitano de Campinas",
    ]),
    "São José dos Campos": ("SP", [
        "Hospital Vivalle",
        "Hospital Policlin",
        "Hospital Pio XII",
        "Hospital São José (Santa Casa)",
        "Hospital Prontil",
        "Hospital Santos Dumont",
        "Hospital Orto — São José dos Campos",
        "Hospital Francisca Júlia",
    ]),
    "Ribeirão Preto": ("SP", [
        "Hospital das Clínicas de Ribeirão Preto (HC-FMRP/USP)",
        "Hospital São Lucas — Ribeirão Preto",
        "Hospital Unimed — Ribeirão Preto",
        "Hospital Santa Lydia",
        "Hospital São Francisco — Ribeirão Preto",
        "Hospital COT (Centro Ortopédico e Traumatológico)",
        "Hospital Electro Bonini",
        "Santa Casa de Ribeirão Preto",
    ]),
    "Florianópolis": ("SC", [
        "Hospital Baía Sul",
        "Hospital de Caridade — Florianópolis",
        "Hospital Universitário Prof. Polydoro Ernani de São Thiago (HU-UFSC)",
        "Hospital Governador Celso Ramos",
        "Hospital Infantil Joana de Gusmão",
        "SOS Cardio — Florianópolis",
        "Hospital Imperial de Caridade",
        "Hospital Regional de São José Dr. Homero de Miranda Gomes",
    ]),
    "Vitória": ("ES", [
        "Hospital Meridional — Vitória",
        "Hospital Santa Rita de Cássia (AFECC)",
        "Hospital Universitário Cassiano Antonio de Moraes (HUCAM/UFES)",
        "Hospital Estadual Dr. Jayme Santos Neves",
        "Hospital Metropolitano — Vitória",
        "Unimed Vitória — Hospital",
        "Hospital Santa Mônica — Vitória",
        "Vitória Apart Hospital",
    ]),
    "Natal": ("RN", [
        "Hospital Universitário Onofre Lopes (HUOL/UFRN)",
        "Hospital do Coração de Natal",
        "Liga Norte Riograndense Contra o Câncer",
        "Hospital Walfredo Gurgel",
        "Hospital Memorial — Natal",
        "Hospital Promater",
        "Hospital da Unimed Natal",
        "Hospital Rio Grande",
    ]),
    "Campo Grande": ("MS", [
        "Hospital Regional de Mato Grosso do Sul Rosa Pedrossian",
        "Hospital Universitário Maria Aparecida Pedrossian (HUMAP/UFMS)",
        "Santa Casa de Campo Grande",
        "Hospital São Julião",
        "Hospital El Kadri",
        "Hospital da Unimed Campo Grande",
        "Hospital Cassems — Campo Grande",
        "Hospital Proncor",
    ]),
    "São Luís": ("MA", [
        "Hospital Universitário da UFMA (HU-UFMA)",
        "UDI Hospital — São Luís",
        "Hospital São Domingos",
        "Hospital Aldenora Bello (Instituto Maranhense de Oncologia)",
        "Hospital Carlos Macieira",
        "Hospital e Clínica São Marcos",
        "Hospital Macroregional de Coroatá",
        "Hospital da Criança — São Luís",
    ]),
}


# ===========================================================================
# 4. NOMES_MASCULINOS (~80 nomes)
# ===========================================================================

NOMES_MASCULINOS = [
    "Carlos", "Pedro", "Lucas", "Rafael", "Bruno", "Thiago", "Gustavo",
    "Rodrigo", "Eduardo", "Felipe", "Marcelo", "Diego", "Henrique",
    "Leonardo", "André", "Fábio", "Vinícius", "Ricardo", "Sérgio",
    "Leandro", "Fernando", "Daniel", "Paulo", "Roberto", "Matheus",
    "Gabriel", "Alexandre", "Guilherme", "João", "Antônio", "José",
    "Márcio", "Ronaldo", "Renato", "Otávio", "Caio", "Tiago",
    "Breno", "Igor", "Mateus", "Samuel", "Victor", "Hugo", "Murilo",
    "César", "Luciano", "Anderson", "Danilo", "Flávio", "Rogério",
    "Júlio", "Augusto", "Renan", "Enzo", "Luan", "Wesley", "Raul",
    "Emanuel", "Adriano", "Marcos", "Nelson", "Heitor", "Bernardo",
    "Arthur", "Miguel", "Davi", "Luís", "Elias", "Tales", "Ramon",
    "Álvaro", "Benício", "Lorenzo", "Théo", "Ravi", "Noah",
    "Cristiano", "Emerson", "Cláudio", "Douglas", "Éverton",
]


# ===========================================================================
# 5. NOMES_FEMININOS (~80 nomes)
# ===========================================================================

NOMES_FEMININOS = [
    "Ana", "Mariana", "Fernanda", "Juliana", "Camila", "Beatriz",
    "Larissa", "Aline", "Patrícia", "Vanessa", "Priscila", "Renata",
    "Gabriela", "Tatiana", "Cristina", "Luciana", "Débora", "Mônica",
    "Isabela", "Adriana", "Carolina", "Bianca", "Amanda", "Letícia",
    "Daniela", "Natália", "Raquel", "Simone", "Elaine", "Viviane",
    "Jéssica", "Cláudia", "Paula", "Carla", "Bruna", "Marina",
    "Alice", "Helena", "Luísa", "Sophia", "Valentina", "Laura",
    "Manuela", "Lívia", "Clara", "Stella", "Cecília", "Lorena",
    "Rafaela", "Luana", "Sabrina", "Andréa", "Sandra", "Flávia",
    "Márcia", "Roberta", "Valéria", "Bárbara", "Milena", "Giovanna",
    "Thaís", "Heloísa", "Aurora", "Lara", "Nicole", "Catarina",
    "Maitê", "Isadora", "Teresa", "Érica", "Kelly", "Vitória",
    "Antônia", "Mirela", "Joana", "Emanuelle", "Paloma", "Nathália",
    "Silvana", "Regina",
]


# ===========================================================================
# 6. SOBRENOMES (~100 sobrenomes brasileiros)
# ===========================================================================

SOBRENOMES = [
    "Silva", "Santos", "Oliveira", "Souza", "Rodrigues", "Ferreira",
    "Alves", "Pereira", "Lima", "Gomes", "Costa", "Ribeiro",
    "Martins", "Carvalho", "Almeida", "Lopes", "Sousa", "Fernandes",
    "Vieira", "Barbosa", "Rocha", "Dias", "Nascimento", "Andrade",
    "Moreira", "Nunes", "Marques", "Machado", "Mendes", "Freitas",
    "Cardoso", "Ramos", "Moraes", "Teixeira", "Castro", "Correia",
    "Monteiro", "Araújo", "Pinto", "Cunha", "Campos", "Azevedo",
    "Melo", "Reis", "Duarte", "Sampaio", "Miranda", "Borges",
    "Leite", "Barros", "Farias", "Medeiros", "Aguiar", "Cavalcanti",
    "Braga", "Nogueira", "Batista", "Rezende", "Fonseca", "Tavares",
    "Peixoto", "Coelho", "Alencar", "Dantas", "Brito", "Camargo",
    "Amaral", "Guimarães", "Paiva", "Assis", "Lacerda", "Siqueira",
    "Antunes", "Coutinho", "Matos", "Queiroz", "Sales", "Pessoa",
    "Vasconcelos", "Bezerra", "Bastos", "Magalhães", "Prado",
    "Arruda", "Porto", "Toledo", "Mesquita", "Santiago", "Esteves",
    "Franco", "Leal", "Pacheco", "Xavier", "Beltrão", "Amorim",
    "Vargas", "Rios", "Rangel", "Sena",
]


# ===========================================================================
# 7. CONVENIOS_LISTA
# ===========================================================================

CONVENIOS_LISTA = [
    "Unimed",
    "Bradesco Saúde",
    "SulAmérica Saúde",
    "Amil",
    "Notre Dame Intermédica",
    "Hapvida",
    "Porto Seguro Saúde",
    "Prevent Senior",
    "Cassi",
    "GEAP Saúde",
    "Eletros",
    "Petrobras Saúde (AMS)",
    "SUS",
    "Saúde Caixa",
    "Postal Saúde",
    "Assim Saúde",
    "Golden Cross",
    "MedSenior",
    "São Cristóvão Saúde",
    "Care Plus",
    "Mediservice",
    "Omint",
    "Allianz Saúde",
    "One Health",
    "Fundação Copel",
    "Cemig Saúde",
    "Banco do Brasil (Cassi)",
    "Caixa de Assistência dos Funcionários do Banco do Brasil",
    "Unimed Seguros",
    "Notredame Intermédica (GNDI)",
]


# ===========================================================================
# 8. COMENTARIOS
# ===========================================================================

COMENTARIOS = {
    "alto": [
        # notas >= 4 — 50 comentários
        "Médico excelente, muito atencioso e dedicado. Recomendo fortemente.",
        "Atendimento de altíssima qualidade. Explicou tudo com clareza e paciência.",
        "Profissional excepcional. Diagnóstico preciso e tratamento eficaz.",
        "Consultório muito bem organizado e médico extremamente competente.",
        "Fiquei impressionado com o nível de conhecimento e cuidado do profissional.",
        "Melhor médico que já consultei. Atencioso, pontual e muito competente.",
        "Resolveu meu problema rapidamente. Saí da consulta com todas as dúvidas esclarecidas.",
        "Profissional brilhante. Fez um diagnóstico que outros médicos não conseguiram.",
        "Ótimo atendimento desde a recepção até o final da consulta.",
        "Médico muito humano e profissional. Me senti acolhida durante todo o atendimento.",
        "Excelente profissional, com vasto conhecimento na área. Super indicado.",
        "Atendeu com muita atenção, explicou detalhadamente o diagnóstico e tratamento.",
        "Pontualíssimo e muito dedicado. Consulta bem aproveitada.",
        "Saí da consulta muito satisfeita. Médico comprometido com o bem-estar do paciente.",
        "Ambiente limpo, equipe simpática e médico extremamente qualificado.",
        "Não poderia estar mais satisfeito. Tratamento surpreendentemente eficaz.",
        "Profissional de referência na especialidade. Muito bem indicado por amigos.",
        "Passou segurança e confiança desde o primeiro momento. Resultado excelente.",
        "O melhor da cidade sem dúvida. Vale cada centavo da consulta.",
        "Muito grato pelo atendimento dedicado. Minha qualidade de vida melhorou muito.",
        "Explica os procedimentos de forma clara e tranquilizadora. Ótimo médico.",
        "Consulta muito bem conduzida. Saí com um plano de tratamento claro e objetivo.",
        "Médico muito preparado, acompanha as últimas novidades da medicina.",
        "Retorno rápido, diagnóstico correto, tratamento eficaz. O que mais poderia querer?",
        "Profissional humano que trata o paciente com respeito e empatia.",
        "Fantástico! Me acompanha há anos e sempre com o mesmo nível de excelência.",
        "Cirurgia perfeita, recuperação dentro do esperado. Equipe nota 10.",
        "Médico com uma paciência incrível. Explicou tudo desenhando para eu entender.",
        "Fui encaminhado por outro médico e não me arrependi. Atendimento impecável.",
        "Consultório moderno, equipe treinada e médico muito atualizado. Recomendo.",
        "Depois de passar por vários profissionais, finalmente encontrei alguém competente.",
        "Fez a diferença no meu tratamento. Sou muito grato por ter encontrado este médico.",
        "Sempre disponível para tirar dúvidas pelo WhatsApp. Muito acessível e humano.",
        "Acompanhamento pós-operatório exemplar. Me senti seguro durante toda a recuperação.",
        "Excelente didática para explicar condições complexas. Saí tranquilo da consulta.",
        "Indicou exames pertinentes sem exageros. Médico ético e responsável.",
        "Meu filho adora esse pediatra. Atencioso e sabe lidar muito bem com crianças.",
        "Tratou minha mãe idosa com muito carinho e respeito. Profissional nota mil.",
        "Conseguiu resolver um problema crônico que me incomodava há anos. Excelente!",
        "Fez um procedimento complexo com maestria. Zero complicações.",
        "A equipe toda merece elogios: da recepcionista ao médico.",
        "Me surpreendeu positivamente. Muito melhor do que eu esperava.",
        "Não é à toa que é tão recomendado. Merece toda a fama que tem.",
        "Mudou minha vida. Desde que comecei o tratamento com ele, melhorei muito.",
        "Profissional ético, transparente sobre os custos e opções de tratamento.",
        "A consulta durou o tempo necessário, sem pressa e sem enrolação.",
        "Senti que ele realmente se importa com os pacientes, não é só mais um número.",
        "Resultados dos exames foram explicados com calma e em linguagem acessível.",
        "O melhor investimento em saúde que já fiz. Voltarei sempre que precisar.",
        "Recomendo de olhos fechados. Um dos melhores profissionais de saúde que conheço.",
    ],
    "medio": [
        # notas 3-4 — 30 comentários
        "Bom profissional, mas a espera foi um pouco longa.",
        "Atendimento satisfatório, embora pudesse explicar melhor o diagnóstico.",
        "Médico competente, mas o consultório poderia ser mais organizado.",
        "Consulta razoável. Resolveu o problema, mas sem muita atenção aos detalhes.",
        "Profissional capacitado, porém a consulta foi mais rápida do que esperava.",
        "Gostei do atendimento, mas tive que esperar mais de 40 minutos.",
        "Médico ok, atende bem mas às vezes parece apressado.",
        "Resultado satisfatório, mas comunicação com o paciente poderia melhorar.",
        "Bom médico, mas a equipe de atendimento deixa a desejar.",
        "Profissional qualificado. A consulta foi produtiva, poderia ser mais empática.",
        "Atendeu bem, mas esperava um pouco mais de atenção para o meu caso.",
        "Médico competente, tratamento funcionou. Ambiente poderia ser melhor.",
        "Consulta dentro do esperado. Nada além, nada aquém.",
        "Profissional dedicado, mas com agenda muito cheia e consulta rápida demais.",
        "Razoável. Resolveu meu problema mas não foi além do básico.",
        "Diagnóstico correto, mas faltou empatia no atendimento.",
        "Boa consulta de modo geral, mas a secretária foi um pouco rude.",
        "Médico sabe o que faz, mas a espera de quase 1 hora é inaceitável.",
        "Tive que ligar várias vezes para conseguir o resultado. Processo burocrático.",
        "Atendimento técnico bom, mas o lado humano poderia ser melhor.",
        "Consulta rápida demais. Precisei voltar para tirar dúvidas que ficaram.",
        "Gostei do tratamento prescrito, mas o preço está acima da média.",
        "Profissional competente. Só acho que poderia ouvir mais o paciente.",
        "Médico tem bom conhecimento, mas o consultório é desatualizado.",
        "Resolveu parcialmente. Tive que buscar complemento com outro especialista.",
        "Atendimento correto, mas nada que me faça indicar entusiasticamente.",
        "Bom profissional, mas não aceitou meu convênio e a particular é cara.",
        "Explicou bem o diagnóstico, mas foi superficial nas orientações de tratamento.",
        "Médico gentil, mas senti falta de um exame mais detalhado.",
        "A experiência foi ok. Nada memorável, mas também nada negativo.",
    ],
    "baixo": [
        # notas < 3 — 20 comentários
        "Esperei mais de uma hora e a consulta durou menos de 10 minutos.",
        "Médico pouco atencioso. Não respondeu adequadamente minhas dúvidas.",
        "Fui indicado mas não gostei. Parecia desinteressado no meu caso.",
        "Consulta muito rápida e superficial. Saí com mais dúvidas do que entrei.",
        "Profissional frio e mecânico. Não me senti acolhido.",
        "O consultório estava desorganizado e o atendimento foi confuso.",
        "Não recomendo. Diagnóstico impreciso e pouca atenção ao histórico do paciente.",
        "Decepcionante. Esperava mais de um profissional tão bem avaliado.",
        "Atendimento ruim, parecia com pressa para encerrar a consulta.",
        "Não voltarei. Difícil de agendar e atendimento abaixo do esperado.",
        "Pediu uma quantidade absurda de exames desnecessários. Pareceu querer lucrar.",
        "O médico atendeu falando no celular. Falta de respeito com o paciente.",
        "Não explicou nada. Receitou e mandou embora. Péssimo.",
        "Indicou um procedimento caro que outro médico disse ser totalmente desnecessário.",
        "Sala de espera lotada, ar-condicionado quebrado e mais de 2 horas de atraso.",
        "Diagnóstico errado. Perdi tempo e dinheiro antes de encontrar o problema real.",
        "Arrogante e impaciente. Não aceita quando o paciente faz perguntas.",
        "Tratamento não funcionou e o médico se recusou a reavaliar sem cobrar outra consulta.",
        "Equipe mal treinada, errou a marcação duas vezes. Quando finalmente fui atendido, a consulta foi medíocre.",
        "O pior atendimento que já tive. Desrespeitoso, grosseiro e incompetente.",
    ],
}


# ===========================================================================
# 9. VALOR_CONSULTA
#    Faixa (min, max) em reais por especialidade.
# ===========================================================================

VALOR_CONSULTA = {
    "Cardiologia": (400, 900),
    "Ortopedia e Traumatologia": (350, 800),
    "Cirurgia Geral": (400, 900),
    "Cirurgia Plástica": (500, 1200),
    "Cirurgia Cardiovascular": (600, 1500),
    "Cirurgia Torácica": (500, 1200),
    "Cirurgia Vascular": (400, 900),
    "Cirurgia de Cabeça e Pescoço": (450, 1000),
    "Cirurgia Pediátrica": (400, 950),
    "Neurocirurgia": (600, 1500),
    "Dermatologia": (300, 700),
    "Ginecologia e Obstetrícia": (300, 700),
    "Pediatria": (250, 550),
    "Neurologia": (400, 900),
    "Oftalmologia": (300, 700),
    "Urologia": (350, 800),
    "Psiquiatria": (400, 900),
    "Oncologia Clínica": (500, 1200),
    "Endocrinologia e Metabologia": (350, 700),
    "Gastroenterologia": (350, 800),
    "Otorrinolaringologia": (300, 650),
    "Anestesiologia": (400, 900),
    "Medicina do Esporte": (300, 650),
    "Geriatria e Gerontologia": (350, 700),
    "Reumatologia": (350, 750),
    "Pneumologia": (350, 750),
    "Nefrologia": (350, 750),
    "Hematologia e Hemoterapia": (400, 900),
    "Infectologia": (350, 750),
    "Medicina Intensiva": (400, 900),
    "Radiologia e Diagnóstico por Imagem": (300, 650),
    "Medicina Nuclear": (400, 850),
    "Patologia / Anatomia Patológica": (300, 600),
    "Medicina de Família e Comunidade": (200, 450),
    "Mastologia": (350, 750),
    "Nutrologia": (300, 650),
    "Acupuntura": (200, 500),
    "Medicina do Trabalho": (250, 500),
    "Medicina Legal e Perícia Médica": (400, 1000),
    "Medicina Física e Reabilitação (Fisiatria)": (300, 650),
    "Genética Médica": (500, 1200),
    "Cirurgia do Aparelho Digestivo": (450, 1000),
    "Coloproctologia": (350, 750),
    "Angiologia": (300, 650),
    "Alergia e Imunologia": (300, 650),
    "Radioterapia": (500, 1100),
    "Medicina de Emergência": (300, 600),
    "Cirurgia da Mão": (400, 900),
    "Homeopatia": (250, 550),
    "Medicina Preventiva e Social": (250, 500),
}


# ===========================================================================
# 10. ASPECTOS_AVALIACAO
# ===========================================================================

ASPECTOS_AVALIACAO = [
    "pontualidade",
    "atendimento",
    "explicação",
    "resultado",
    "ambiente",
    "acolhimento",
    "tempo de consulta",
    "retorno",
    "infraestrutura",
    "equipe",
]


# ===========================================================================
# 11. NOMES_PACIENTES (~60 primeiros nomes)
# ===========================================================================

NOMES_PACIENTES = [
    "Ana", "Carlos", "Maria", "João", "Fernanda", "Lucas", "Camila",
    "Pedro", "Beatriz", "Rafael", "Juliana", "Bruno", "Larissa",
    "Gustavo", "Aline", "Rodrigo", "Patrícia", "Eduardo", "Vanessa",
    "Felipe", "Renata", "Diego", "Gabriela", "Henrique", "Tatiana",
    "Leonardo", "Cristina", "André", "Luciana", "Fábio", "Débora",
    "Vinícius", "Mônica", "Ricardo", "Isabela", "Sérgio", "Adriana",
    "Leandro", "Mariana", "Thiago", "Marta", "Roberto", "Sandra",
    "Márcio", "Viviane", "Alexandre", "Simone", "Daniel", "Bianca",
    "Mateus", "Carolina", "Samuel", "Amanda", "Jorge", "Natália",
    "Cláudio", "Regina", "Elias", "Flávia",
]
